import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Provider from "@/utils/Providers";

const ubuntu = Ubuntu({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <main className="flex justify-center items-center h-screen">
          <Provider>{children}</Provider>
        </main>
      </body>
    </html>
  );
}
